// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1UTsKssGMHBCdKDgwWVKanE4WbWcdHzI',
    appId: '1:1013031778451:web:f343a35210fad67e273566',
    messagingSenderId: '1013031778451',
    projectId: 'second-project-8c431',
    authDomain: 'second-project-8c431.firebaseapp.com',
    storageBucket: 'second-project-8c431.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7GpQQPCJR1Uv-3u8RW7Pu6gle5jrb2iA',
    appId: '1:1013031778451:android:cf7b9c152a70b0cd273566',
    messagingSenderId: '1013031778451',
    projectId: 'second-project-8c431',
    storageBucket: 'second-project-8c431.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsoX4JrtZMNywrpnemF8aUlMEBr5-SyJM',
    appId: '1:1013031778451:ios:81802fd32f810e4c273566',
    messagingSenderId: '1013031778451',
    projectId: 'second-project-8c431',
    storageBucket: 'second-project-8c431.appspot.com',
    iosBundleId: 'com.example.thirdAppTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsoX4JrtZMNywrpnemF8aUlMEBr5-SyJM',
    appId: '1:1013031778451:ios:1b6f0eb488566cf1273566',
    messagingSenderId: '1013031778451',
    projectId: 'second-project-8c431',
    storageBucket: 'second-project-8c431.appspot.com',
    iosBundleId: 'com.example.thirdAppTwo.RunnerTests',
  );
}
